# Generated by Django 4.2.2 on 2023-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tflitemodel",
            name="mlmodel_path",
            field=models.CharField(
                editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
