# Generated by Django 4.2.4 on 2023-09-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TFLiteModel",
            new_name="MLModel",
        ),
        migrations.RenameField(
            model_name="MLModel",
            old_name="file_path",
            new_name="tflite_path",
        ),
        migrations.RenameField(
            model_name="MLModel",
            old_name="layers_sizes",
            new_name="tflite_layers",
        ),
        migrations.AlterField(
            model_name="ModelParams",
            name="tflite_model",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="params",
                to="train.mlmodel",
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="coreml",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="coreml_layers",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="coreml_path",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="tflite",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="data_type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_models",
                to="train.trainingdatatype",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="tflite_layers",
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="tflite_path",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
