# Generated by Django 4.2.4 on 2023-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tflitemodel",
            name="is_coreml",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
