# Generated by Django 4.2.4 on 2023-08-30 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0002_coremlmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreMLModelParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", models.BinaryField()),
                (
                    "coreml_model",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="train.coremlmodel",
                    ),
                ),
            ],
        ),
    ]
