on:
  push:
    paths:
      - '.github/workflows/dart-format.yml'
      - '**.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
