on:
  push:
    paths:
      - '.github/workflows/flutter-android.yml'
      - '**.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ github.run_id }}
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Test
        run: |
          cd fed_kit_client/
          flutter test
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 18
          cache: gradle
      - name: Build APK
        run: |
          cd fed_kit_client/
          flutter build apk
