on:
  push:
    paths:
      - '.github/workflows/flutter-ios.yml'
      - '**.plist'
      - '**.swift'
      - '**.xcconfig'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
      - name: Build
        run: |
          cd fed_kit_client/
          flutter build ios --no-codesign
