on:
  push:
    paths:
      - '.github/workflows/flutter-integration.yml'
      - '**.py'
      - 'flutter/**.dart'
      - 'flutter/**pubspec.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd backend/
          sh integration_test_setup.sh
      - uses: arduino/setup-protoc@v2
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: |
          cd backend/
          python manage.py runserver &
          cd ../flutter
          dart pub global activate protoc_plugin
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          flutter pub get
          sh gen_code.sh
      - name: Test
        run: |
          cd flutter/
          flutter test --run-skipped
      - name: Analysis
        run: |
          cd flutter/
          flutter analyze
