on:
  push:
    paths:
      - '.github/workflows/flutter.yml'
      - '**.dart'
      - '**pubspec.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
          cd ../flutter
          flutter pub get
      - name: Test
        run: |
          cd fed_kit_client/
          flutter test
          cd ../flutter
          flutter test
      - name: Analysis
        run: |
          cd fed_kit_client/
          flutter analyze
          cd ../flutter
          flutter analyze
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
