on:
  push:
    paths:
      - '.github/workflows/flutter-ios.yml'
      - '**.dart'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
      - name: Test
        run: |
          cd fed_kit_client/
          flutter test
      - name: Build
        run: |
          cd fed_kit_client/
          flutter build ios --no-codesign
