on:
  push:
    paths:
      - '.github/workflows/flutter-client-ios.yml'
      - '**.plist'
      - '**.swift'
      - '**.xcconfig'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download MNIST data set
        run: |
          cd fed_kit_client/ios/Runner/Utils/
          mkdir MNIST
          cd MNIST
          curl -LO https://github.com/FedCampus/FedKit/files/12543877/MNIST.zip
          unzip MNIST.zip
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
      - name: Build
        run: |
          cd fed_kit_client/
          flutter build ios --no-codesign
