on:
  push:
    paths:
      - '.github/workflows/intellij-formatting.yml'
      - '**.java'
      - '**.kt'
      - '**.xml'
      - '**.gradle'
jobs:
  intelliJ:
    runs-on: ubuntu-latest
    name: IntelliJ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check IntelliJ Formatting
        uses: sidhant92/intellij-format-action@v1
        with:
          tool_name: 'IntelliJ Diff'
          github_token: ${{ secrets.github_token }}
          fail_on_changes: true
          path: '.'
          file_mask: '*.java,*.kt,*.xml,*.gradle'
