on:
  push:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '**.swift'
jobs:
  swiftformat:
    runs-on: macos-latest
    name: Check swiftformat
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Swift tools
        run: |
          curl -LO https://github.com/nicklockwood/SwiftFormat/releases/download/0.51.13/swiftformat.zip
          unzip swiftformat
      - name: Format Swift code
        run: ./swiftformat --verbose .
      - name: Verify formatted code is unchanged
        run: |
          rm -rf __MACOSX swiftformat swiftformat.zip
          git diff --exit-code HEAD
